Started by user [8mha:////4K7SonDTAuGL7kSjRxIwkgedPGlCQunhdvEn8vXX5ES2AAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy+EgZe/dLi1CL94qTUjNSiRAAwkGaUwgAAAA==[0mSwadesh Behera
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building in workspace /var/jenkins_home/workspace/fdc-prod/BOSA-Daily-Issue-Report
The recommended git tool is: NONE
using credential vinay-github
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/fdc-prod/BOSA-Daily-Issue-Report/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/The-Frontdoor-Collective/fdc-etl.git # timeout=10
Fetching upstream changes from https://github.com/The-Frontdoor-Collective/fdc-etl.git
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
using GIT_ASKPASS to set credentials vinay-github
 > git fetch --tags --force --progress -- https://github.com/The-Frontdoor-Collective/fdc-etl.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/develop^{commit} # timeout=10
Checking out Revision 99886e00f85823d366ea89e1a6e8b2356be489bd (refs/remotes/origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 99886e00f85823d366ea89e1a6e8b2356be489bd # timeout=10
Commit message: "Update daily_exceptions_report_prod.py"
 > git rev-list --no-walk 99886e00f85823d366ea89e1a6e8b2356be489bd # timeout=10
[BOSA-Daily-Issue-Report] $ /bin/sh -xe /tmp/jenkins676880366222235332.sh
+ cd python_scripts
+ python3 daily_exceptions_report_prod.py 13
Location Name :  BOSA
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/fdc-prod/BOSA-Daily-Issue-Report/python_scripts/daily_exceptions_report_prod.py", line 95, in <module>
    rows = [ list(i) for i in cursor.fetchall()]
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/cursor.py", line 882, in fetchall
    (rows, eof) = self._connection.get_rows()
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 446, in get_rows
    raise err
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 443, in get_rows
    rows = self._protocol.read_text_result(self._socket, self._server_version, count=count)
  File "/var/jenkins_home/.local/lib/python3.9/site-packages/mysql/connector/protocol.py", line 347, in read_text_result
    raise get_exception(packet)
mysql.connector.errors.DatabaseError: 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
Build step 'Execute shell' marked build as failure
Finished: FAILURE
